#
#
# Copyright 2016 The Symphony Software Foundation
#
# Licensed to The Symphony Software Foundation (SSF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

language: java

before_install:
  - "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash"
  - "nvm install 6.10"
  - "nvm use 6.10"
  - "npm update -g npm"

install: true

jdk:
  - oraclejdk8

env:
  global:
    - secure: "ua1x4WxxXqdKsKmm1n097k3deKAUNWujeWeOZgLVPoEcN6XxrXmxAIV1LZkkOu6ll6wxkQjzleQhtUUEGFplIzLaflg1ntWafnnf8NmwjIvcVo75lSJ9rofdS8a0g6ulQam1BwRrjhuBgA/PbVnzIIdiAY6HwB/Qp4CKogPxAzE231F0LSrlzNxVI8+2aoEyCvX3RUx1yYNcNAXmpcDSVFI7Nn/no8jv1vkuqNaUcQvuQlmwOLsfu8AjolKXTd8VuK0gLArvM2KPrBGKYLsoGTWb2W6AXSZWDBk6XCBe7wrWfsEDERE8KvlxYsdsiieYqXTPzr0Hk0aO4MoCw0I6JK0O86R0EmoEn6eUqPlTgqtPgn4cNm1wVYbmz3SgKi8JxRuA/GBjOtCDrfZ7H7RsPMbMVcx988i8n3GkUnKUilf9bGHqgZOgCJEe/aF12JDIvJO81cTgPu2IFQjQkcHeQcheSQKzHfGWEq3804BHuTx3luhCbhnLCvLByU8taRttfobcHVRw54UBNP4HtkukEQUurhJAsmT69OdUrZpd821FrAkB59GeD8JFkNVmUYDp9jkXZ27cUW8zdbOb+8xLcyXa8FKnghAiF4VuqMyPGL7sanQGjRlRPYmX6daUIUBpFdlYO9RPRQVzw75XxBQjlBKidMm+TSFQ8vbwlBxcfIw="

addons:
  coverity_scan:
    project:
      name: "symphonyoss/App-Integrations-Salesforce"
      description: "Build submitted via Travis CI"
    notification_email: "integrations-team@symphony.com"
    build_command_prepend: "mvn clean"
    build_command:   "mvn -Denv=dev -DsymphonySkipUnitTests=true install"
    branch_pattern: "dev"

script:
- "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" && $TRAVIS_BRANCH =~ dev ]]; then mvn clean deploy -Pversioneye,whitesource -Pcobertura -DtransitiveDependencies=true --settings settings.xml ; fi"
- "if [[ \"$TRAVIS_PULL_REQUEST\" != \"false\" ]]; then mvn clean package -Pcobertura; fi"

- npm install
# Cannot run on external PRs due to https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
- "if [[ $TRAVIS_PULL_REQUEST -eq 'false' ]]; then npm run whitesource; fi;"
# Break the build, if any Whitesource policy violation is found
- "if [[ -e 'ws-log-policy-violations.json' ]]; then echo 'Found Whitesource Policy violation, build failed.' ; exit -1; fi;"

after_success:
- bash <(curl -s https://codecov.io/bash)